name: Docker Build

on:
  workflow_dispatch:
  push:
    tags:
      - build-responses
    branches:
      - master

jobs:
  docker-build:
    name: 'Docker response push'
    runs-on: ubuntu-latest
    permission:
      packages: write

  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: gradle/wrapper-validation-action@v1
    - name: Login to GitHub Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push image
      uses: docker/build-push-action@v4
      with:
        context: ./responses/app
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}
    - name: Tag & Push branch image
      uses: docker/build-push-action@v4
      with:
        context: ./responses/app
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}
          ghcr.io/${{ github.repository }}:${{ github.ref_name }}
    - name: Tag & Push latest image
      if: github.ref_name == 'master'
      uses: docker/build-push-action@v4
      with:
        context: ./responses/app
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}
          ghcr.io/${{ github.repository }}:latest